name: Deploy Updates

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.USERNAME }}/polywhale
            git pull origin main
            
            source venv/bin/activate
            pip install -r requirements.txt
            
            # Update .env file
            echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > src/.env
            
            sudo cp infra/tracker.service /etc/systemd/system/
            sudo cp infra/frontend.service /etc/systemd/system/
            sudo systemctl daemon-reload
            
            sudo systemctl restart tracker
            sudo systemctl restart frontend
